<Project>
  <PropertyGroup>
    <Version>3.0.0-beta.0</Version>
    <Authors>Neolution</Authors>
    <Company>Neolution AG</Company>
    <Copyright>Copyright © Neolution AG</Copyright>
    <PackageProjectUrl>https://github.com/neolution-ch/Neolution.Extensions.Caching</PackageProjectUrl>
    <RepositoryUrl>https://github.com/neolution-ch/Neolution.Extensions.Caching</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
